### ISSUE TITLE
runtime error when calling lua function from C++, passing a const char*

### ISSUE THREAD

**Issue by TrianglesPCT** [decimad/luabind-deboostified#14]
Trying to convert from luabind(the boost version) to this one, getting error at startup.

const char* path = "..\code\script\?.lua;"
luabind::call_function(_State, "set_path",path);

It seems to be trying to find the class_id for "const char", not finding anything, and then reporting that const char is not a registered class.

" Trying to use unregistered class: char const *"

**Comment by the-nic** [comment]
I think there's simply missing a semicolon in the first line..

**Comment by decimad** [comment]
I can reproduce this behaviour. Working on a fix.

**Comment by decimad** [comment]
Added the missing string literal overload (latest commit). Pleare let me know if it works for you.

**Comment by TrianglesPCT** [comment]
the-nic: this was psuedo code, the real code was too complex to post, but yes it has a missing semi colon
decimad: thx I'll give it a try

**Comment by bagobor** [comment]
I just tested master branch and std::string, const std::string&, and const char* works.

**Comment by decimad** [comment]
Great, thank you!
