### ISSUE TITLE
Calling C++ functions with default arguments from Lua

### ISSUE THREAD

**Issue by Xottab-DUTY** [decimad/luabind-deboostified#40]
When I try to call exported function with default args luabind says, that matching overload is not found and requires to send all arguments.
Is there a solution to use default args?

The following code working normally in the old luabind (~beta7-devel.rc4) but wont work with current version
```c++
void g_send(NET_Packet& P, bool bReliable = false, bool bSequential = true, bool bHighPriority = false, bool bSendImmediately = false)
{
     Level().Send(P, net_flags(bReliable, bSequential, bHighPriority, bSendImmediately));
}

inline static void CLevel_Export(lua_State* luaState)
{
    module(luaState, "level")
    [
        def("send", &g_send) //allow the ability to send netpacket to level
    ];
};
````
```lua
function exampleFunction()
    local packet = net_packet()
    ...  -- doing something with packet here
    level.send(packet); -- new luabind wants all 5 arguments
end
```

P.S. because of this we are forced to manually create overloads on C++ part (you can look [here](https://github.com/qweasdd136963/xray-16/commit/c37d8f4e49c92fe226a5958954cc9a6a1ab18c93#diff-6406a20125b80b4558968e681b4d4717R577))

**Comment by decimad** [comment]
Are you aware how this works with the "original" luabind? My understanding is that at the moment you take the address of the method, the syntactic sugar of default arguments of a method declaration/definition is gone.

**Comment by Xottab-DUTY** [comment]
> Are you aware how this works with the "original" luabind?

Can't say how it works in the original version..
> My understanding is that at the moment you take the address of the method, the syntactic sugar of default arguments of a method declaration/definition is gone.

Is there a way to use the syntactic sugar?

**Comment by decimad** [comment]
Well, until I see proof of the other case, I assume it is not possible to automatically deduce default arguments given a function pointer, since the default arguments are not part of the function type

**Comment by Xottab-DUTY** [comment]
Can we explicitly tell to luabind default arguments, then?

**Comment by decimad** [comment]
Well it would be possible to specify default arguments and let luabind genrate the wrapper functions, I guess

**Comment by Xottab-DUTY** [comment]
Can you help with how to specify them?)

**Comment by decimad** [comment]
This requires enhancement of the library itself first

**Comment by Xottab-DUTY** [comment]
Ah.. Okay. I just don't know how to do this. Will leave it as is for now...
