### ISSUE TITLE
pure_out_value with discard_result

### ISSUE THREAD

**Issue by atom0s** [decimad/luabind-deboostified#8]
In the standard Luabind I can def a function with both of these such as:

``` c++
.def( "GetString",      &IConfiguration::GetString, luabind::pure_out_value(_4) + luabind::discard_result )
```

With the boostless version you provide, I cannot seem to find a way to make both of these values work.

Is there a new method of handling both? At the moment I am trying the similar format of:

``` c++
.def("GetConfigString", &IScriptManager::GetConfigString, pure_out_value<4>() + discard_result())
```

But this does not work.

**Comment by ltjax** [comment]
I think you can use 
```
.def("GetConfigString", &IScriptManager::GetConfigString, policy_list<pure_out_value<4>, discard_result>())

```

**Comment by ltjax** [comment]
I'm not sure this was really ported from the with-boost version, but it seems like some form of using meta::join is now required for this, since policies are now, as the readme says, lists with one element.

Like this:
```c++
.def("GetConfigString", &IScriptManager::GetConfigString, meta::join<pure_out_value<4>, discard_result>())

```

**Comment by atom0s** [comment]
I landed up writing wrappers for Lua to use the configuration stuff I showed above. Not a huge deal now since it was a while back. If I decide to do any other adjustments I'll check out your suggestion though, thanks.

**Comment by decimad** [comment]
Closing this, ltjax pointed to the correct construct for policy aggregation.
